apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      name: bookapp
      labels:
        app: bookapp
    spec:
      containers:
      - name: bookapp
        image: keerthan25 / useraccount
        ports:
        - containerPort: 8080
        
        ---
        
apiVersion: v1
kind: Service
metadata:
  name: np
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 31000
  selector:
    app: bookapp 
        
 
 
